apiVersion: v1
kind: Pod
metadata:
  name: my-first-demo
  labels:
    app: my-first-demo
spec:
  containers:
    - name: my-first-demo
      image: ghcr.io/cunmingliu/zhangxun/service2:latest
      ports:
        - containerPort: 80
