apiVersion: v1
kind: Service
metadata:
  name: my-first-demo-svc1
  labels:
    app: my-first-demo
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
  selector:
    app: my-first-demo
